[package]
name = "rust-file-organizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
serde_json = "1.0.59"
readable_byte = "0.1.14"
fs_extra = "1.2.0"